import { DEFAULT_SITE_THEME } from './siteTheme';

export const HERO_CTA_COLOR_SCHEMES = {
  default: {
    title: 'Default - matches site buttons',
    backgroundColor: 'linear-gradient(to right, var(--btn-brown), var(--btn-brown-hover))',
    textColor: 'var(--bg-paper)',
    borderColor: '#000000CC',
    hoverBackgroundColor: 'linear-gradient(to right, var(--btn-brown), var(--btn-brown-hover))',
    hoverTextColor: 'var(--bg-paper)',
  },
  white: {
    title: 'White',
    backgroundColor: '#FFFFFF',
    textColor: DEFAULT_SITE_THEME.textColor,
    borderColor: '#FFFFFF',
    hoverBackgroundColor: DEFAULT_SITE_THEME.secondaryBackgroundColor,
    hoverTextColor: DEFAULT_SITE_THEME.textColor,
  },
  charcoal: {
    title: 'Charcoal',
    backgroundColor: '#2F342F',
    textColor: '#F3F4F1',
    borderColor: '#2F342F',
    hoverBackgroundColor: '#4D5853',
    hoverTextColor: '#F3F4F1',
  },
  sage: {
    title: 'Sage',
    backgroundColor: '#6A715A',
    textColor: '#F3F4F1',
    borderColor: '#6A715A',
    hoverBackgroundColor: '#4D5853',
    hoverTextColor: '#F3F4F1',
  },
  linen: {
    title: 'Linen',
    backgroundColor: '#E7E1D4',
    textColor: '#2F342F',
    borderColor: '#E7E1D4',
    hoverBackgroundColor: '#F3F4F1',
    hoverTextColor: '#2F342F',
  },
  terracotta: {
    title: 'Terracotta',
    backgroundColor: '#8C5A3C',
    textColor: '#FFF8F0',
    borderColor: '#8C5A3C',
    hoverBackgroundColor: '#6D4C3D',
    hoverTextColor: '#FFF8F0',
  },
  rosewood: {
    title: 'Rosewood',
    backgroundColor: '#5C2B33',
    textColor: '#FCEFF1',
    borderColor: '#5C2B33',
    hoverBackgroundColor: '#3F1E24',
    hoverTextColor: '#FCEFF1',
  },
  coastal: {
    title: 'Coastal',
    backgroundColor: '#2F4858',
    textColor: '#F7F9FB',
    borderColor: '#2F4858',
    hoverBackgroundColor: '#203642',
    hoverTextColor: '#F7F9FB',
  },
  amber: {
    title: 'Amber',
    backgroundColor: '#A76932',
    textColor: '#FEFBF3',
    borderColor: '#A76932',
    hoverBackgroundColor: '#7A4A22',
    hoverTextColor: '#FEFBF3',
  },
  outline: {
    title: 'Transparent Outline (White)',
    backgroundColor: 'transparent',
    textColor: '#FFFFFF',
    borderColor: '#FFFFFF',
    hoverBackgroundColor: '#FFFFFF',
    hoverTextColor: '#2F342F',
  },
  outlinePaper: {
    title: 'Transparent Outline (Paper)',
    backgroundColor: 'transparent',
    textColor: '#E7E1D4',
    borderColor: '#E7E1D4',
    hoverBackgroundColor: '#E7E1D4',
    hoverTextColor: '#2F342F',
  },
  outlineIvory: {
    title: 'Transparent Outline (Ivory)',
    backgroundColor: 'transparent',
    textColor: '#F3F4F1',
    borderColor: '#F3F4F1',
    hoverBackgroundColor: '#F3F4F1',
    hoverTextColor: '#2F342F',
  },
  outlineCharcoal: {
    title: 'Transparent Outline (Charcoal)',
    backgroundColor: 'transparent',
    textColor: '#2F342F',
    borderColor: '#2F342F',
    hoverBackgroundColor: '#2F342F',
    hoverTextColor: '#F3F4F1',
  },
  outlineSage: {
    title: 'Transparent Outline (Sage)',
    backgroundColor: 'transparent',
    textColor: '#6A715A',
    borderColor: '#6A715A',
    hoverBackgroundColor: '#6A715A',
    hoverTextColor: '#F3F4F1',
  },
  softBlack: {
    title: 'Soft Black',
    backgroundColor: '#1A1A1A',
    textColor: '#F3F4F1',
    borderColor: '#1A1A1A',
    hoverBackgroundColor: '#333333',
    hoverTextColor: '#F3F4F1',
  },
  inkwell: {
    title: 'Inkwell',
    backgroundColor: '#0D0D0D',
    textColor: '#E7E1D4',
    borderColor: '#0D0D0D',
    hoverBackgroundColor: '#2A2A2A',
    hoverTextColor: '#E7E1D4',
  },
  graphite: {
    title: 'Graphite',
    backgroundColor: '#3B3B3B',
    textColor: '#F3F4F1',
    borderColor: '#3B3B3B',
    hoverBackgroundColor: '#555555',
    hoverTextColor: '#F3F4F1',
  },
  espresso: {
    title: 'Espresso',
    backgroundColor: '#2C1E14',
    textColor: '#F3F4F1',
    borderColor: '#2C1E14',
    hoverBackgroundColor: '#4A3628',
    hoverTextColor: '#F3F4F1',
  },
  midnight: {
    title: 'Midnight',
    backgroundColor: '#1B2430',
    textColor: '#E7E1D4',
    borderColor: '#1B2430',
    hoverBackgroundColor: '#2F3E4E',
    hoverTextColor: '#E7E1D4',
  },
  ivory: {
    title: 'Ivory',
    backgroundColor: '#F3F4F1',
    textColor: '#2F342F',
    borderColor: '#C7D1CD',
    hoverBackgroundColor: '#E7E1D4',
    hoverTextColor: '#2F342F',
  },
  parchment: {
    title: 'Parchment',
    backgroundColor: '#EDE8DB',
    textColor: '#2F342F',
    borderColor: '#D4CFC2',
    hoverBackgroundColor: '#F3F4F1',
    hoverTextColor: '#2F342F',
  },
  cream: {
    title: 'Cream',
    backgroundColor: '#FAF8F4',
    textColor: '#4D5853',
    borderColor: '#E7E1D4',
    hoverBackgroundColor: '#F3F4F1',
    hoverTextColor: '#2F342F',
  },
  bone: {
    title: 'Bone',
    backgroundColor: '#F0EBE1',
    textColor: '#3B3B3B',
    borderColor: '#D8D2C6',
    hoverBackgroundColor: '#FAF8F4',
    hoverTextColor: '#2F342F',
  },
  pearl: {
    title: 'Pearl',
    backgroundColor: '#F8F6F2',
    textColor: '#4D5853',
    borderColor: '#E0DCD4',
    hoverBackgroundColor: '#FFFFFF',
    hoverTextColor: '#2F342F',
  },
} as const;

export type HeroCtaColorSchemeKey = keyof typeof HERO_CTA_COLOR_SCHEMES;

export const DEFAULT_HERO_CTA_COLOR_SCHEME: HeroCtaColorSchemeKey = 'default';

export const HERO_CTA_COLOR_SCHEME_OPTIONS = Object.entries(HERO_CTA_COLOR_SCHEMES).map(
  ([value, scheme]) => ({
    title: scheme.title,
    value,
  })
);
