import { defineArrayMember, defineField, defineType } from 'sanity';

const stringArrayOf = (title: string) =>
  defineField({
    name: title
      .replace(/[^a-zA-Z0-9]+(.)/g, (_, char: string) => char.toUpperCase())
      .replace(/^[A-Z]/, (char) => char.toLowerCase()),
    title,
    type: 'array',
    of: [defineArrayMember({ type: 'string' })],
  });

export default defineType({
  name: 'commissionsPageSettings',
  title: 'Commissions Page Settings',
  type: 'document',
  groups: [
    { name: 'intro', title: 'Intro' },
    { name: 'form', title: 'Form Copy' },
    { name: 'pricing', title: 'Pricing & Sizes' },
    { name: 'summary', title: 'Summary' },
  ],
  fields: [
    defineField({
      name: 'pageTitle',
      title: 'Page Title',
      type: 'string',
      group: 'intro',
      initialValue: 'Commission a Custom Piece',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'introLead',
      title: 'Intro Lead',
      type: 'text',
      rows: 2,
      group: 'intro',
      initialValue: 'Thank you for your interest!',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'checklistHeading',
      title: 'Checklist Heading',
      type: 'string',
      group: 'intro',
      initialValue: 'A few notes before we begin:',
      validation: (rule) => rule.required(),
    }),
    defineField({
      ...stringArrayOf('Checklist Items'),
      group: 'intro',
      description: 'Short bullets shown near the top of the page.',
      initialValue: [
        'Commission spots are limited, so be sure to reserve early.',
        "Upload an inspiration photo that reflects what you're envisioning.",
        'Images should be your own original photos, clear and well lit.',
        "Still deciding? I'm happy to help you choose the strongest reference.",
        "Include any notes about specific colors or palettes you'd like to complement your space.",
        'Pricing is based on size, and a 20% upfront, non-recoverable investment secures your spot and covers materials.',
      ],
      validation: (rule) => rule.required().min(1),
    }),
    defineField({
      name: 'introClosing',
      title: 'Intro Closing',
      type: 'text',
      rows: 4,
      group: 'intro',
      initialValue:
        "To request a spot or receive exact pricing, simply fill out the form below. There's no need to have every detail figured out; share your photos and initial ideas, and we'll refine the vision together. I can't wait to create something beautiful with you!",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'informationSectionTitle',
      title: 'Information Section Title',
      type: 'string',
      group: 'form',
      initialValue: 'Your Information',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'nameLabel',
      title: 'Name Label',
      type: 'string',
      group: 'form',
      initialValue: 'Your Name',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'namePlaceholder',
      title: 'Name Placeholder',
      type: 'string',
      group: 'form',
      initialValue: 'Your full name',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'emailLabel',
      title: 'Email Label',
      type: 'string',
      group: 'form',
      initialValue: 'Your Email',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'emailPlaceholder',
      title: 'Email Placeholder',
      type: 'string',
      group: 'form',
      initialValue: 'example@email.com',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'descriptionLabel',
      title: 'Description Label',
      type: 'string',
      group: 'form',
      initialValue: 'Artwork Description or Notes',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'descriptionPlaceholder',
      title: 'Description Placeholder',
      type: 'text',
      rows: 2,
      group: 'form',
      initialValue: 'Tell us about your ideas (colors, style, subject)...',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'referenceImagesLabel',
      title: 'Reference Images Label',
      type: 'string',
      group: 'form',
      initialValue: 'Reference Images (optional)',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'referenceImagesDropzoneTitle',
      title: 'Reference Images Dropzone Title',
      type: 'string',
      group: 'form',
      initialValue: 'Drag & drop inspiration images',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'referenceImagesDropzoneHint',
      title: 'Reference Images Dropzone Hint',
      type: 'string',
      group: 'form',
      initialValue: 'or click to browse. JPG, PNG, or WEBP. Max 25MB total.',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'canvasSectionTitle',
      title: 'Canvas Section Title',
      type: 'string',
      group: 'form',
      initialValue: 'Canvas Selections',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'canvasSizeLabel',
      title: 'Canvas Size Label',
      type: 'string',
      group: 'form',
      initialValue: 'Canvas Size',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'customSizeLabel',
      title: 'Custom Size Label',
      type: 'string',
      group: 'form',
      initialValue: 'Custom Size',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'customWidthLabel',
      title: 'Custom Width Label',
      type: 'string',
      group: 'form',
      initialValue: 'Custom Width (inches)',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'customHeightLabel',
      title: 'Custom Height Label',
      type: 'string',
      group: 'form',
      initialValue: 'Custom Height (inches)',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'quantityLabel',
      title: 'Quantity Label',
      type: 'string',
      group: 'form',
      initialValue: 'Quantity',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'customSizeNote',
      title: 'Custom Size Note',
      type: 'text',
      rows: 3,
      group: 'form',
      initialValue:
        "Note: I'll source the canvas for custom sizes, and pricing may increase depending on the dimensions.",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'itemEstimateLabel',
      title: 'Item Estimate Label',
      type: 'string',
      group: 'form',
      initialValue: 'Estimated Total',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'addCanvasButtonLabel',
      title: 'Add Canvas Button Label',
      type: 'string',
      group: 'form',
      initialValue: 'Add Another Canvas',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'removeCanvasButtonLabel',
      title: 'Remove Canvas Button Label',
      type: 'string',
      group: 'form',
      initialValue: 'Remove Item',
      validation: (rule) => rule.required(),
    }),
    defineField({
      ...stringArrayOf('Predefined Canvas Options'),
      group: 'pricing',
      description: 'Sizes shown in the canvas dropdown. Use the format 24" X 36".',
      initialValue: [
        '24" X 36"',
        '24" X 48"',
        '30" X 40"',
        '6" X 6"',
        '4" X 6"',
        '5" X 7"',
        '8" X 8"',
        '10" X 10"',
        '12" X 12"',
        '14" X 14"',
        '18" X 18"',
        '20" X 20"',
        '8" X 10"',
        '8" X 16"',
        '9" X 12"',
        '10" X 20"',
        '11" X 14"',
        '12" X 16"',
        '12" X 24"',
        '14" X 18"',
        '16" X 20"',
        '18" X 24"',
        '20" X 24"',
        '22" X 28"',
        '24" X 30"',
        '20" X 36"',
        '12" X 36"',
        '36" X 48"',
        '30" X 30"',
        '36" X 36"',
        '48" X 48"',
        '48" X 60"',
      ],
      validation: (rule) => rule.required().min(1),
    }),
    defineField({
      name: 'pricePerSquareInch',
      title: 'Price Per Square Inch',
      type: 'number',
      group: 'pricing',
      initialValue: 1,
      validation: (rule) => rule.required().min(0.01),
    }),
    defineField({
      name: 'minimumCommissionPrice',
      title: 'Minimum Commission Price',
      type: 'number',
      group: 'pricing',
      initialValue: 250,
      validation: (rule) => rule.required().min(0),
    }),
    defineField({
      name: 'depositPercentage',
      title: 'Deposit Percentage',
      type: 'number',
      group: 'pricing',
      description: 'Used for the upfront estimate in the summary.',
      initialValue: 20,
      validation: (rule) => rule.required().min(0).max(100),
    }),
    defineField({
      name: 'summarySectionTitle',
      title: 'Summary Section Title',
      type: 'string',
      group: 'summary',
      initialValue: 'Commission Summary',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'totalLabel',
      title: 'Total Label',
      type: 'string',
      group: 'summary',
      initialValue: 'Total Commission Cost',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'depositLabel',
      title: 'Deposit Label',
      type: 'string',
      group: 'summary',
      initialValue: 'Upfront Deposit',
      validation: (rule) => rule.required(),
    }),
    defineField({
      ...stringArrayOf('Summary Notes'),
      group: 'summary',
      description: 'Short notes shown under the calculator totals.',
      initialValue: [
        'Smaller canvas sizes 14" x 18" and under have fixed prices to account for creation time and materials.',
        'The calculator provides an approximate price based on size. This form is just a request for a commission, and I will reach out to discuss the details and provide a final quote.',
        'I may not be able to accept all commissions due to time constraints but will do my best to accommodate. Thank you so much for your interest in my work! I look forward to working with you.',
      ],
      validation: (rule) => rule.required().min(1),
    }),
    defineField({
      name: 'submitButtonLabel',
      title: 'Submit Button Label',
      type: 'string',
      group: 'summary',
      initialValue: 'Submit Commission Request',
      validation: (rule) => rule.required(),
    }),
  ],
  preview: {
    prepare() {
      return {
        title: 'Commissions Page Settings',
      };
    },
  },
});
